export const todaysData = {
  totalUsers: 19248,
  totalMarketPlace: 862,
  totalRetail: 194,
  totalTransaction: 20,
  avarageSession: 8,
  topFiveUniversities: [
    {
      collegeName: "www.stanford.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.harvard.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.uchicago.edu/en",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.harvard.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.ox.ac.uk",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
  ],

  topFiveSellers: [
    {
      name: "John Doe",
      email: "sales@stanford.edu",
      profilePicture: 'https://i.ibb.co/JxFYSQ7/saller1-avatar.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 2",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/YNbKn3Z/seller-avatar-2.png',
      marketListing: 10,
      retailListing: 14,
      payout: 30,
    },
    {
      name: "John Doe 3",
      email: "sales@uchicago.edu",
      profilePicture: 'https://i.ibb.co/hKwLwL8/seller-avatar-3.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 4",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/tYB26P7/seller-avatar-4.png',
      marketListing: 12,
      retailListing: 16,
      payout: 32,
    },
    {
      name: "John Doe 5",
      email: "sales@ox.ac.uk",
      profilePicture: 'https://i.ibb.co/VLRRcqk/seller-avatar-5.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
  ],
  genderRation: [
    ["Male", 30],
    ["Female", 60],
    ["Other", 10],
  ],
  topThreeCategories: [
    { icon: "https://i.ibb.co/M8wS7zx/top-cat-icon-1.png", title: "Dresses", amount: "19K" },
    { icon: "https://i.ibb.co/vVCw3X7/top-cat-icon-2.png", title: "Footwear ", amount: "8K" },
    { icon: "https://i.ibb.co/brXSj0b/top-cat-icon-3.png", title: "Electronics", amount: "15K" },
  ],
  transactionDetails: {
    totalTransaction: 9248,
    payouts: 862,
    totalShippingAmount: 194,
  },
};

export const yesterdayData = {
  totalUsers: 20500,
  totalMarketPlace: 1100,
  totalRetail: 215,
  totalTransaction: 35,
  avarageSession: 10,
  topFiveUniversities: [
    {
      collegeName: "www.stanford.edu",
      users: 62,
      marketListing: 10,
      retailListing: 15,
    },
    {
      collegeName: "www.harvard.edu",
      users: 67,
      marketListing: 9,
      retailListing: 11,
    },
    {
      collegeName: "www.uchicago.edu/en",
      users: 40,
      marketListing: 7,
      retailListing: 14,
    },
    {
      collegeName: "www.harvard.edu",
      users: 78,
      marketListing: 10,
      retailListing: 18,
    },
    {
      collegeName: "www.ox.ac.uk",
      users: 50,
      marketListing: 9,
      retailListing: 14,
    },
  ],

  topFiveSellers: [
    {
      name: "John Doe",
      email: "sales@uchicago.edu",
      profilePicture: 'https://i.ibb.co/VLRRcqk/seller-avatar-5.png',
      marketListing: 15,
      retailListing: 25,
      payout: 40,
    },
    {
      name: "John Doe 2",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/tYB26P7/seller-avatar-4.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 3",
      email: "sales@stanford.edu",
      profilePicture: 'https://i.ibb.co/JxFYSQ7/saller1-avatar.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 4",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/hKwLwL8/seller-avatar-3.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 5",
      email: "sales@ox.ac.uk",
      profilePicture: 'https://i.ibb.co/YNbKn3Z/seller-avatar-2.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
  ],

  genderRation: [
    ["Male", 35],
    ["Female", 55],
    ["Other", 10],
  ],
  topThreeCategories: [
    { icon: "https://i.ibb.co/M8wS7zx/top-cat-icon-1.png", title: "Dresses", amount: "15K" },
    { icon: "https://i.ibb.co/vVCw3X7/top-cat-icon-2.png", title: "Footwear ", amount: "10K" },
    { icon: "https://i.ibb.co/brXSj0b/top-cat-icon-3.png", title: "Electronics", amount: "18K" },
  ],
  transactionDetails: {
    totalTransaction: 10500,
    payouts: 950,
    totalShippingAmount: 240,
  },
};

export const thisWeekData = {
  totalUsers: 19248,
  totalMarketPlace: 862,
  totalRetail: 194,
  totalTransaction: 20,
  avarageSession: 8,
  topFiveUniversities: [
    {
      collegeName: "www.stanford.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.harvard.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.uchicago.edu/en",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.harvard.edu",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
    {
      collegeName: "www.ox.ac.uk",
      users: 42,
      marketListing: 8,
      retailListing: 12,
    },
  ],

  topFiveSellers: [
    {
      name: "John Doe",
      email: "sales@stanford.edu",
      profilePicture: 'https://i.ibb.co/YNbKn3Z/seller-avatar-2.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 2",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/tYB26P7/seller-avatar-4.png',
      marketListing: 10,
      retailListing: 14,
      payout: 30,
    },
    {
      name: "John Doe 3",
      email: "sales@uchicago.edu",
      profilePicture: 'https://i.ibb.co/JxFYSQ7/saller1-avatar.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 4",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/hKwLwL8/seller-avatar-3.png',
      marketListing: 12,
      retailListing: 16,
      payout: 32,
    },
    {
      name: "John Doe 5",
      email: "sales@ox.ac.uk",
      profilePicture: 'https://i.ibb.co/VLRRcqk/seller-avatar-5.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
  ],
  genderRation: [
    ["Male", 30],
    ["Female", 60],
    ["Other", 10],
  ],
  topThreeCategories: [
    { icon: "https://i.ibb.co/M8wS7zx/top-cat-icon-1.png", title: "Dresses", amount: "19K" },
    { icon: "https://i.ibb.co/vVCw3X7/top-cat-icon-2.png", title: "Footwear ", amount: "8K" },
    { icon: "https://i.ibb.co/brXSj0b/top-cat-icon-3.png", title: "Electronics", amount: "15K" },
  ],
  transactionDetails: {
    totalTransaction: 9248,
    payouts: 862,
    totalShippingAmount: 194,
  },
};

export const thisMonthData = {
  totalUsers: 20500,
  totalMarketPlace: 1100,
  totalRetail: 215,
  totalTransaction: 35,
  avarageSession: 10,
  topFiveUniversities: [
    {
      collegeName: "www.stanford.edu",
      users: 62,
      marketListing: 10,
      retailListing: 15,
    },
    {
      collegeName: "www.harvard.edu",
      users: 67,
      marketListing: 9,
      retailListing: 11,
    },
    {
      collegeName: "www.uchicago.edu/en",
      users: 40,
      marketListing: 7,
      retailListing: 14,
    },
    {
      collegeName: "www.harvard.edu",
      users: 78,
      marketListing: 10,
      retailListing: 18,
    },
    {
      collegeName: "www.ox.ac.uk",
      users: 50,
      marketListing: 9,
      retailListing: 14,
    },
  ],

  topFiveSellers: [
    {
      name: "John Doe",
      email: "sales@uchicago.edu",
      profilePicture: 'https://i.ibb.co/VLRRcqk/seller-avatar-5.png',
      marketListing: 15,
      retailListing: 25,
      payout: 40,
    },
    {
      name: "John Doe 2",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/tYB26P7/seller-avatar-4.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 3",
      email: "sales@stanford.edu",
      profilePicture: 'https://i.ibb.co/YNbKn3Z/seller-avatar-2.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 4",
      email: "sales@harvard.edu",
      profilePicture: 'https://i.ibb.co/hKwLwL8/seller-avatar-3.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
    {
      name: "John Doe 5",
      email: "sales@ox.ac.uk",
      profilePicture: 'https://i.ibb.co/JxFYSQ7/saller1-avatar.png',
      marketListing: 8,
      retailListing: 12,
      payout: 24,
    },
  ],

  genderRation: [
    ["Male", 35],
    ["Female", 55],
    ["Other", 10],
  ],
  topThreeCategories: [
    { icon: "https://i.ibb.co/M8wS7zx/top-cat-icon-1.png", title: "Dresses", amount: "15K" },
    { icon: "https://i.ibb.co/vVCw3X7/top-cat-icon-2.png", title: "Footwear ", amount: "10K" },
    { icon: "https://i.ibb.co/brXSj0b/top-cat-icon-3.png", title: "Electronics", amount: "18K" },
  ],
  transactionDetails: {
    totalTransaction: 10500,
    payouts: 950,
    totalShippingAmount: 240,
  },
};
